ROpdebee/mb-userscripts

- mb_supercharged_caa_edits.user.js
Tested with [Edit #78562367](https://musicbrainz.org/edit/78562367), front covers should usually have the same aspect ratio as back covers for regular jewel cases and can possibly also include spines.
I also checked the [docs](https://musicbrainz.org/doc/Release/Packaging) for more likely non-square packaging types while I was at it, but I found none. Only the _Snap Case_ could be another possible candidate - but I have never seen one and there is no example image, only a description:
> A digipak-like case held together with a "snapping" plastic closure.
> [caa edits] Add fatbox to non-square packagings

- rollup/plugin-userscript.ts
- Correct the file extension
- Import the module using a file URL for compatibility with Windows, otherwise drive letters are recognized as an invalid protocol
I could not resist and had to try out the new features of mb_upload_to_caa_from_url, so I tried to setup the build environment on my computer ❤️
> Fix import of metadata files

- .eslintrc.cjs
- package.json
- src/.eslintrc.cjs
- src/mb_blind_votes/index.tsx
- src/mb_enhanced_cover_art_uploads/atisket.tsx
- src/mb_enhanced_cover_art_uploads/index.tsx
- Run ESLint for .jsx and .tsx files too (was missing in `package.json` and `.eslintrc.cjs`).
- Also includes fixes for most of these new linter warnings (except any type in catch clauses).
- Enable warnings for variable declarations without initialisation. This makes it easier to ensure they have type annotations (to prevent them from being any type) before disabling the warning locally.
> Run ESLint for .tsx files & Use it to spot variables without inferred types

- mb_caa_dimensions.user.js
Fixes #57
It was calculating the dimensions of the static thumbnail instead. Unfortunately we can't properly calculate the dimensions of a PDF yet (or maybe ever).
> Don't display dimensions on queued PDF uploads

- mb_collapse_work_attributes.user.js
I'm not a huge fan of this approach, since it will now match `artist/.../workPageThatShouldNotBeProcessed`, but it's the only way I can find to fix this without using `@include` instead.
Tested on FF/TM and FF/VM and confirmed to work on both. I'm assuming it should work on other combinations too.
This shouldn't be an issue for other `@match` patterns in this script as they all end in `*`.
Fixes #59
> Include `mb_collapse_work_codes` on paginated artist pages

- rollup.ts
* Revert 56691144ce64123f38fb91f932fc3ba224a4daec
* Change build to never minify top-level declarations in modules, not even in 3rd-party code
This should make bug reports a lot easier, and stack traces useful again.
Closes #50
> Revert minifying full scripts

- .eslintrc.cjs
- tsconfig.json
* Disable `no-implicit-any-catch` since it generates false warnings for TS 4.4 (where caught errors are `unknown` by default)
* Enable `noImplicitOverride` in TS. Doesn't generate any warnings yet, so it's a good idea to enable it for the future.
> Linting improvements

- src/mb_enhanced_cover_art_uploads/index.tsx
Noticed this while testing for #69. We were adding the URL to the done set before it was actually done, and this prevents retrying the same URL if it failed previously. Fixing by adding the URLs to the done set after the image was queued.
> Fix duplicate image detection on error

- package-lock.json
- package.json
- src/lib/util/xhr.ts
- src/mb_enhanced_cover_art_uploads/index.tsx
- src/mb_enhanced_cover_art_uploads/providers/amazon.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
- src/mb_enhanced_cover_art_uploads/providers/discogs.ts
- src/mb_enhanced_cover_art_uploads/providers/qobuz.ts
- src/mb_enhanced_cover_art_uploads/providers/tidal.ts
- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
Little bit of refactoring because I dislike the interface of `GM_xmlhttpRequest` and since we're using a wrapper, we can do better.
* Make the `method` parameter optional, default to `GET` since that'll be used most often.
* Move the `url` to a separate parameter, since it's always required anyway, whereas other options might not be. Also accept `URL` instances.
> Refactor `gmxhr`

- src/mb_enhanced_cover_art_uploads/providers/bandcamp.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
The changes from #152 prevent extracting any covers if the main release does not have a cover. However, there could still be separate track covers which we can extract.
Other smaller fixes:
* Don't log an error if a track is known to have no covers.
* Don't log messages about track cover extraction if there is no tracklist (e.g. for `/track/` URLs).
> fix(caa upload): extract track covers for releases without main cover

- src/mb_enhanced_cover_art_uploads/index.ts
May close #193 
In older versions, spam-clicking the provider button will lead to the same URL being processed multiple times, and possibly enqueued multiple times too, depending on the interleaving of certain async operations. To prevent this, we're now keeping a set of URLs which are currently in progress, and skip all processing of a URL entirely if it's already being processed.
> fix(caa upload): prevent processing URL if it's already in progress

- package-lock.json
- src/lib/MB/URLs.ts
- src/lib/MB/advanced-relationships.ts
- src/mb_enhanced_cover_art_uploads/docs/supported_providers.md
- src/mb_enhanced_cover_art_uploads/form.ts
- src/mb_enhanced_cover_art_uploads/index.ts
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- src/mb_enhanced_cover_art_uploads/seeding/index.ts
- src/mb_enhanced_cover_art_uploads/seeding/vgmdb.tsx
- tests/lib/MB/URLs.test.ts
- tests/mb_enhanced_cover_art_uploads/form.test.ts
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-empty-list-when-URL-does-not-exist_2275831759/recording.har
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-empty-list-when-no-release-is-attached-to-URL_3987713515/recording.har
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-release-ID-for-URL_2258567196/recording.har
Closes #62.
We can't extract all images through the VGMdb provider, so we'll add a VGMdb seeder on logged-in pages so that images that require logging in can be extracted from the page itself, and added through seeding parameters.
> feat(caa upload): add VGMdb seeder

- src/mb_enhanced_cover_art_uploads/index.ts
Some refactoring in the previous PRs removed some local variable `origin`, but forgot to remove its usage. `origin` is also a `window` variable, so it's now resolving to that, and the edit note always says "Seeded from musicbrainz.org".
Urgent, hotfixing.
> fix(caa upload): fix bad seeding origin in edit notes

- src/mb_enhanced_cover_art_uploads/index.ts
- src/mb_enhanced_cover_art_uploads/seeding/atisket.tsx
I though MB polyfilled this one for us, but apparently it doesn't.
I'm not sure how I feel about including a whole bunch of polyfill code just for that single method (it's not actually polyfilling anything but `array.at`, but just happens to include a bunch of other stuff for core-js internals I guess?). At the same time, I want the source code to be modern and not have to be limited to old ES versions.
For this method though, I'm not sure whether it's worth the bloat... But on the other hand, the script also runs on pages other than MB, where polyfills might not be available.
Possibly closes #214
> fix(caa upload): polyfill `array.at`

- src/mb_enhanced_cover_art_uploads/seeding/atisket.tsx
Spotify images no longer have a file extension, so we should not assume that everything after the last dot is a file extension.
Fixes #216.
> Handle images without file extension

- src/lib/util/async.ts
- tests/lib/util/async.test.ts
The previous implementation could start to retry a call if the call took a long time to complete.
Closes #223
> fix(lib): wait until function returns before retrying in `retryTimes`

- src/mb_enhanced_cover_art_uploads/fetch.ts
- tests/mb_enhanced_cover_art_uploads/fetch.test.ts
* Include actual MIME type returned by server in error message.
* Provide specific error message when content type is textual, as this may mean that the user is trying to use an unsupported provider.
Closes #238
> fix(caa upload): improve error message on invalid file types

- README.md
- mb_collapse_work_attributes.user.js
MB offers all of its functionality itself now. We'll push a final update which displays a message to the user, recommending them to uninstall the script. In a few days, we should remove the whole script.
See #246.
> chore(coll work attrs)!: deprecate now-unnecessary userscript

- src/mb_enhanced_cover_art_uploads/providers/amazon.ts
The Amazon provider fails to extract the embedded JSON because it is no longer at the beginning of a new line but indented since a recent update.
Fixes #272.
> fix(caa upload): Adapt to new Amazon page source code indentation

- .github/renovate.json
Grouping all non-major updates makes it possible for the PR to be blocked by one dependency, as is currently happening in #268. This isn't ideal.
renovate will still group monorepos and only raise PRs on weekends, so it should still reduce dependency update spam. Grouping all updates doesn't reduce dependency update spam that much, since renovate will keep pushing new updates to the existing grouped PR, which still sends many emails.
> chore(deps): don't group all non-major renovate updates

- .eslintignore
- .eslintrc.cjs
- package-lock.json
- package.json
- src/lib/MB/EditNote.ts
Add a linter for deprecated function calls.
Replace `trimRight` (deprecated) with `trimEnd`.
> fix: remove usage of deprecated functions

- .github/actions/setup/action.yml
`npm ci` often takes more than 15s per job, and we're running it in many different jobs. These changes could decrease that to a few seconds (or skip it entirely), which should significantly speed up CI.
Cherry-picked from #254, confirmed to be working properly there.
> ci: speed up `npm install`

- src/mb_enhanced_cover_art_uploads/fetch.ts
In #175, we removed duplicate extensions for GIF, PNG, and JPEG, but we forgot to do the same for PDF.
Cherry-picked from #254
> fix(caa upload): also clean up PDF filenames

- .browserslistrc
- babel.config.cjs
- package-lock.json
- package.json
- src/lib/util/domain_dispatch.ts
- src/lib/util/urls.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/index.ts
- src/mb_enhanced_cover_art_uploads/maximise.ts
- src/mb_enhanced_cover_art_uploads/providers/discogs.ts
- src/mb_enhanced_cover_art_uploads/providers/musicbrainz.ts
- src/mb_enhanced_cover_art_uploads/providers/soundcloud.ts
- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- src/mb_enhanced_cover_art_uploads/seeding/parameters.ts
- types/ESProposals.d.ts
These changes should massively reduce the size of the built scripts without changing anything functionally. Cherry-picked from #254.
Summary:
* Drop support for some old browsers which don't support userscripts, to eliminate some transpilations for these browsers.
* Use a babel plugin to convert async/await into promises where possible, instead of using babel's regenerator. The regenerator is still included (mainly for some generators/async generators), but this eliminates most of the weird `switch` statements and leads to shorter, more natural code.
* Remove any usage of `Array.prototype.at` since it's not supported in most browsers and including the polyfill is way more expensive than using alternative means of using negative array indices.
Excluded from this PR: Switching to …
> perf(build): reduce size of built scripts

- mb_qol_inline_recording_tracks.user.js
- mb_qol_seed_recording_disambiguation.user.js
- mb_validate_work_codes.user.js
* Fix URL matching of multi-page artist works for MB: Validate Work Codes (same as #61)
* Run `MB: QoL: Seed the batch recording comments script` and `MB: QoL: Inline all recording's tracks on releases` on `/release/*/disc1` pages. These are reachable through `/track/` URLs.
* Fix `MB: QoL: Inline all recording's tracks on releases` match pattern to exclude `notmusicbrainz.org` etc.
> fix: URL matching

- src/mb_enhanced_cover_art_uploads/docs/supported_providers.md
- src/mb_enhanced_cover_art_uploads/maximise.ts
- tests/unit/mb_enhanced_cover_art_uploads/maximise.test.ts
Closes #80 again.
Fast-tracked this because it's been bothering me for quite a while.
> feat(ecau): grab Apple Music original source images

- src/mb_enhanced_cover_art_uploads/maximise.ts
As pointed out in https://github.com/ROpdebee/mb-userscripts/pull/327#discussion_r773853556, the URL will always be different because of an unconditional domain change. This changes the check to only compare URL pathnames to prevent problems due to domain names.
> fix(ecau): prevent duplicate/broken Apple Music source URLs

- src/mb_enhanced_cover_art_uploads/providers/rateyourmusic.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/rateyourmusic.test.ts
Fixes #329.
~This ran 715 test cases on my machine, so CI should do the same. Does it though?~ It does, ignore me, I got confused as I only added two URL test cases but of course each URL tests translates into 3 smaller test cases (matching, ID extraction, and checking the dispatch map) 🤦‍♂️
> feat(ecau): support RateYourMusic single URLs

- .eslintrc.cjs
- src/lib/util/array.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/base.test.ts
Also adds an ESLint rule to warn about this next time.
Fixes #330
> fix(ecau): properly sort track numbers in track image comment

- src/mb_enhanced_cover_art_uploads/providers/amazon.ts
Not an exhaustive list, it's super tedious to find these. The IDs that work on .com don't work on .fr and others, so you'd need to scroll through a whole bunch of search results to find a placeholder image. These should include the most common ones. If anyone finds new placeholders, they can report them and we can add them.
Also, amazon.ca doesn't use placeholder images but instead shows an error, e.g. on https://www.amazon.ca/dp/B000Q3KSMQ. The JSON contains `null`, so the provider will show an error message. Perhaps we should handle this edge case better through some better logging calls, but that should probably wait until #81 to make sure the logging messages are actually displayed.
Fixes #324 (partially, at least).
> fix(ecau): filter out more placeholder images in Amazon provider

- babel.config.cjs
- src/mb_enhanced_cover_art_uploads/maximise.ts
Previously, there would be transpilations performed by both babel
itself and the transform-async-to-promises plugin. This led to
conflicts. Instead, we'll let the plugin do all transformations for
async generators, and babel will only do plain generators.
For ECAU, this also completely removes the need for the regenerator
runtime, yet again shrinking the compiled script size significantly.
This is a proper fix for #351 and should allow us to update to 0.8.18 of babel-plugin-transform-async-to-promises.
> fix(build): properly transpile async generators

- mb_bulk_copy_work_codes.user.js
In some languages, the agency code keys are translated leading to
issues pasting the codes. For example, in German, the key for ASCAP
is "ASCAP-ID" while the script expects the English "ASCAP ID". This
is a temporary fix to normalise such translations. Some exceptions,
most notably PRS, may still not work correctly in translations. We
need a better fix for the script to work in other languages, but for
that, some parts would need quite invasive changes.
Fixes #349.
> fix(work codes): support translated agency IDs

- .github/renovate.json
- .github/workflows/deploy.yml
- .github/workflows/renovate-check.yml
- build/check-scripts-unchanged.ts
- build/deploy.ts
- build/versions.ts
- package-lock.json
- package.json
Allow renovate to automatically merge certain dependency updates (patch and minor bumps to dev dependencies; pinning dependencies, and lock file maintenance) without even creating a PR. This should reduce many of the notifications.
Renovate will check that all CI jobs pass before attempting to merge. I've added a new CI job that will fail build/test/lint/typecheck as normal, but will also fail if the built scripts would be changed in any way. This ensures that we don't let Renovate automatically merge updates to dev dependencies that cause changes in production (e.g. babel). In case of failures, Renovate will open a real PR instead.
We'll still get real PRs in the following cases:
* Major bumps to dev dependencies (on weekends)
* Any update to prod dependencies (on weekends)
* Any dev …
> build: reduce renovate spam

- .github/renovate.json
The previous changes caused renovate to perform lock file maintenance every time it ran, leading to too much commits on `main`.
> build(renovate): monthly lock file maintenance

- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/seeding/atisket.tsx
Contrary to atj's mirror, since we can't easily get the release ID from marlonob's original version, we don't seed the release URL but seed the direct image URL instead. We did the release URL workaround for atj's mirror so that we could properly maximise the Apple Music images to JPEG/PNG depending on source format, but we now have a better maximisation strategy for Apple Music, so it's no longer relevant.
Closes #251
> feat(ecau): seed from marlonob's atisket

- src/lib/logging/guiSink.scss
- src/lib/logging/guiSink.tsx
- src/lib/util/array.ts
- src/mb_enhanced_cover_art_uploads/App.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/ui/main.scss
- src/mb_enhanced_cover_art_uploads/ui/main.tsx
I finally went ahead and did it, the new status message GUI has arrived 🎉
Also improves logging of current progress while fetching.
Fixes #81.
Now that we have a bit more real estate to work with, perhaps it's time to rewrite the log messages to log the full URL instead of just the filename? E.g. Discogs changed their URLs _again_ and now they always have the same filename for the same release.
> feat(ecau): improved logging message display

- src/mb_enhanced_cover_art_uploads/maximise.ts
- src/mb_enhanced_cover_art_uploads/providers/discogs.ts
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/clears-the-cache-entry-on-failure_963532173.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-for-subsequent-requests_598889563.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-while-maximising-images_2688171962.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/extracts-covers-for-release_2308446907.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/throws-on-non-existent-release_1189313548.warc
- tests/unit/mb_enhanced_cover_art_uploads/maximise.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/discogs.test.ts
* Fix maximisation of single URLs.
* Fix displayed filenames.
I don't like that we have to do this, but it is what it is. Stupid Discogs with their security through obscurity.
> fix(ecau): new Discogs image URLs

- src/lib/util/array.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
> perf(ecau): refactor sync generators to prevent babel regenerator

- src/lib/util/urls.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/maximise.ts
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/providers/discogs.ts
- tests/unit/mb_enhanced_cover_art_uploads/maximise.test.ts
More maximisation!
Exceptions for 7digital have been removed, exception for Apple Music has been changed to mark the `/source` URLs that are likely broken as such, and we'll skip warning the user when we can't fetch a likely broken image.
Closes #392.
We should also perhaps create some more IMU tickets to add Jamendo and DatPiff.
> feat(ecau): bump IMU to latest version

- README.md
- mb_bulk_copy_work_codes.user.js
The GEMA repertoire handler is fairly straightforward (there is only one agency code and one ISWC per work which has to be extracted) and works for the English and the German search. Pagination of the results does not cause problems, the mutation observer correctly catches all these events, except for the inital page load which might load the results of the last visit again and requires an inital handler.
It took me a while to figure out why the code of the first commit alone failed to work, although I've implemented it the same way as the CISAC handler. Then I found out that I have to drop the explicit JSON serialization of the "clipboard data" and directly feed the raw object into the GM storage function to make it work.
Violentmonkey and Tampermonkey already do the JSON serialization …
> Create a GEMA repertoire handler

- tests/test-data/__recordings__/apple-music-provider_2401788145/extracting-images_1310741912/throws-on-non-existent-Apple-Music-release_3871375527.warc
- tests/test-data/__recordings__/apple-music-provider_2401788145/extracting-images_1310741912/throws-on-non-existent-iTunes-release_3050089140.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/clears-the-cache-entry-on-failure_963532173.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-for-subsequent-requests_598889563.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-while-maximising-images_2688171962.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/extracts-covers-for-release_2308446907.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/throws-on-non-existent-release_1189313548.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/apple_music.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/discogs.test.ts
No production changes this time around, but two test fixes:
* Discogs changed their URL format so our test data needed to be evolved. Prod code still works fine.
* The Apple Music release we were using to test 404 pages is online again, so we need to use another release for this test.
Affected HTTP recordings are updated as well. I've regenerated all of the other recordings too, but haven't committed these changes since they don't affect the script.
Closes #419.
Adding [skip-cd] tag since no prod code is touched and otherwise it'd deploy the changes from #422 in this PR.
> test(ecau): fix tests after upstream provider changes

- mb_bulk_copy_work_codes.user.js
See https://github.com/ROpdebee/mb-userscripts/commit/1a163ace55acb4cd29d04c3e6dae8b6c0ea8dc74#commitcomment-69876519.
A dirty workaround for a dirty hack which is used by the GEMA website. I would have preferred my original solution to simply drop the JSON serialization, but if this helps to make the userscript work again with Chrome+Tampermonkey, let's do that 😝
> Restore `JSON.stringify()` for GEMA repertoire search

- mb_supercharged_caa_edits.user.js
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/providers/archive.ts
- tests/test-data/__recordings__/archive-provider_3534120302/extracting-images_1310741912/extracts-covers-for-item-with-a-filename-that-requires-URL-encoding_3946155584.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/archive.test.ts
Various minor improvements for ECAU and supercharged cover art edits, based on the [suggestions by chaban](https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/57?u=kellnerd) in the forums.
- Support new packaging types (one of them is non-square) and release statuses for supercharged cover art edits
- Use the latest version of Image Max URL for compatibility with new Violentmonkey (beta) versions (untested)
- Support filenames on archive.org which require URL encoding in ECAU:
- New test for the given example to cover this case.
- I'm restoring path separators after URL encoding to be on the safer side, although I haven't seen examples for full paths "including directory paths" yet, as per https://github.com/ROpdebee/mb-userscripts/blob/d04c2514a93e5a45a61cba0087 …
> Minor updates for the cover art scripts

- src/mb_enhanced_cover_art_uploads/seeding/musicbrainz.tsx
- src/mb_enhanced_cover_art_uploads/seeding/parameters.ts
- tests/unit/mb_enhanced_cover_art_uploads/seeding/parameters.test.ts
Closes #444
This doesn't change the behaviour on atisket, and redirecting to the preferred MBS version is supported by jesus2099's script there.
> fix(ecau): maintain MB domain when seeding from cover art page

- tests/test-data/__recordings__/getting-URLs-for-release_1054398333/can-omit-URLs-which-are-ended_3862782763.warc
- tests/test-data/__recordings__/getting-URLs-for-release_1054398333/can-omit-duplicate-URLs_4045665903.warc
- tests/test-data/__recordings__/getting-URLs-for-release_1054398333/retrieves-all-URLs_515713061.warc
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-empty-list-when-URL-does-not-exist_2275831759.warc
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-empty-list-when-no-release-is-attached-to-URL_3987713515.warc
- tests/test-data/__recordings__/getting-releases-for-URLs_3409569510/returns-release-ID-for-URL_2258567196.warc
Every time I run the tests, these recordings are getting regenerated. I'm not sure why it's happening, probably some dependency update, but I'm too lazy to figure that out. Let's just update the recordings so it stops regenerating them.
> test: update recordings for `fetch`

- .github/workflows/deploy.yml
I broke CI in #457, copy-paste error 🙁 Oops.
Via PR because I've restricted direct pushes to main and it's faster to submit a PR and merge it than to disable that restriction, push, and re-enable it. (Although it might've been faster considering I had to write all of this.) (And now that I wrote that, it definitely would've been faster…)
> ci: fix finding PR number in deployment

- build/changelog.ts
- build/plugin-update-notifications.ts
- build/plugin-userscript.ts
- build/rollup.ts
- package-lock.json
- src/lib/update-notifications/banner.scss
- src/lib/update-notifications/index.tsx
- src/lib/util/dom.ts
- src/lib/util/versions.ts
- src/mb_enhanced_cover_art_uploads/App.ts
- src/mb_enhanced_cover_art_uploads/index.ts
- src/mb_enhanced_cover_art_uploads/ui/main.tsx
- src/types/rollup-consts.d.ts
- tests/unit/build/changelog.test.ts
- tests/unit/build/plugin-userscript.test.ts
- tests/unit/lib/util/versions.test.ts
Fixes #455. Depends on #457.
This allows the scripts to automatically notify when its recent updates contain new features. Some changes to the build were necessary to inject the necessary information too. Unfortunately the script still needs to explicitly call a function to get these to be displayed, I did not manage to inject that during the build.
All new features since the last "acknowledged" (= closing the notification) will be grouped together per script.
Some caveats:
- The notifications can be dismissed, but that dismissal won't be shared between beta.MB and main MB because it's using local storage to track which version was last dismissed. Can't do much about that except for using `GM.getValue` and `GM.setValue`, but that would lead to issues with content vs page context scripts. …
> feat: update notifications

- README.md
It was pointing to the raw file, not the rendered one.
> docs: fix changelog link in README

- package-lock.json
- package.json
- src/mb_enhanced_cover_art_uploads/form.ts
- src/mb_enhanced_cover_art_uploads/tsconfig.json
- tests/unit/mb_enhanced_cover_art_uploads/form.test.ts
So apparently my previous experimentation didn't go far enough and it turns out we don't actually need jQuery to get MB to handle the drop event. The reason we were using jQuery was that we can't "officially" instantiate our own `DropEvent`s with a `FileList` with our own files in the `dataTransfer` property (either because of read-only properties, private constructors, or some other security precaution). However, I never tried just defining the necessary properties using `Object.defineProperty`, which can circumvent the readonly status. Turns out, that just works. :tada:
Fixes #440.
Tested successfully on:
> fix(ecau): drop images without jQuery

- src/mb_enhanced_cover_art_uploads/seeding/atisket.tsx
Fixes #438. Also fixes a new issue introduced by #464 (seeding still worked, but it was using image links instead of release links).
If we merge #451 before this one, I'll also do the refactoring to use the new implementation here so we get a retry loop.
> fix(ecau): don't require dimensions to load before inserting seed links on a-tisket

- src/lib/util/async.ts
- src/lib/util/dom.ts
- src/mb_multi_external_links/index.ts
https://github.com/ROpdebee/mb-userscripts/pull/473#issuecomment-1153312621
Probably not worth a new version, but `skip cd` will cause useless updates to be made to 2 of the 3 TS scripts on the next PR anway, and it'll bother me otherwise.
\+ A small fix for `split links` and refactoring to use `logFailure`, not worth separate PRs and deployments IMO.
> refactor(lib): allow tree-shaking the prototype input setter

- mb_qol_seed_recording_disambiguation.user.js
Partial fix for #480.
Ideally we should extract it from the JSON-LD embedded on the page, or some other source that doesn't rely as much on the DOM structure. However, we'll do that after the script is rewritten to TypeScript. I'm going to leave the issue open until then though.
> fix(seed disamb): update release title extraction for new MBS version

- src/mb_enhanced_cover_art_uploads/docs/supported_providers.md
- tests/unit/mb_enhanced_cover_art_uploads/providers/docs.test.ts
While adding new providers yesterday, I kept on forgetting to add them to the `supported_providers.md` file. This adds a test to verify that the new provider has an entry in that file.
> test(ecau): test for missing providers in docs

- src/mb_caa_dimensions/DisplayedImage.tsx
Fixed this previously for other images, but missed the same mistake in queued upload thumbnails.
Follow up for #495.
> fix(caa dims): fix order of dimensions on queued upload thumbnails

- src/mb_enhanced_cover_art_uploads/ui/main.tsx
Fixes issue reported by [chaban in the forums](https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/84?u=ropdebee).
~It's a bit of a hack, but it should prevent double pasting from causing dupes. I've described some possible alternatives in the comments, but they would probably either be quite complex, not user-friendly, or both.~ ~I should really test stuff before I push. This doesn't work :facepalm: Something is removing the space we're appending (I think an MB event handler?), so I'm working on another solution.~
We'll now clear the input as soon as we're handling it, and set the URL we're processing as the input's placeholder as an "acknowledgement".
> fix(ecau): prevent accidental double pastes

- src/lib/MB/types.ts
- src/mb_multi_external_links/index.ts
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/91
https://github.com/metabrainz/musicbrainz-server/pull/2497 changed some internals that we were using to get the external links editor object (specifically, https://github.com/metabrainz/musicbrainz-server/pull/2497/files#diff-20a3affccc96c36d0a67c0ca98ebc7010590a1adc067eeea57147b0302bf1add).
This is only in beta for now, so for now we'll try both the fixed and old implementation and use the one that worked, but once this goes into prod we should remove the old implementation.
> fix(split links): adjust links editor properties for new MBS version

- build/plugin-logger.ts
- build/rollup.ts
- src/mb_caa_dimensions/index.ts
- src/mb_enhanced_cover_art_uploads/index.ts
- src/mb_multi_external_links/index.ts
I keep forgetting to enable the logger in new or migrated scripts, all of them need it, and the code is mostly identical anyway. Let's automatically inject it when building it so it'll always be present.
Cherry-picked from #499.
> build: automatically insert logger boilerplate config

- src/mb_caa_dimensions/Image.ts
- tests/unit/mb_caa_dimensions/Image.test.ts
- tests/unit/mb_caa_dimensions/test-utils/mock-data.ts
In most cases, we can use the full-size URL as the cache key. However, for release groups, the full-size URL is the CAA-redirected front image. When the RG cover is changed, this URL stays the same, so the cache isn't invalidated properly. Also, for PDFs, we were using the derived JP2 URL as the cache key instead of the PDF URL itself. This change fixes both by separating the cache key from the image URL we query. For RGs, the cache key will now be the thumbnail URL, which will change if the RG cover is changed.
Also reworked the tests to do better tests for these URL transformations and extractions. More work is needed there though, I think some of the earlier tests are doing duplicated work. Ideally, the URL transformation and extraction would be split off from the CAAImage class, but I …
> fix(caa dims): separate cache key from full-size URL

- src/mb_enhanced_cover_art_uploads/fetch.ts
- tests/unit/mb_enhanced_cover_art_uploads/fetch.test.ts
We were marking a provider as done even if some (or even all!) of the images failed to fetch. This change will allow retrying when one or more images failed to fetch. Only the failed images will be retried, the ones that are already queued will be skipped via pre-existing logic.
> fix(ecau): allow retrying provider URLs when some images failed

- src/lib/logging/guiSink.scss
- src/lib/logging/guiSink.tsx
- src/lib/util/array.ts
Discogs URLs tend to overflow the logging banner. Firefox performs sub-optimal line breaking (it breaks in the middle of the URL), but Chrome performs no line breaking at all.
To fix this, we'll insert word-break hints in front of all forward slashes, which should convince the browsers to perform proper line breaking. However, since it's still possible that an enormous URL without forward slashes will appear, we're also setting a CSS property to allow all browsers to do arbitrary word breaking in case it's really necessary.
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/96?u=ropdebee
I'm borrowing a modified version of `insertBetween` from #499, so whenever work on that recommences, it should be synced.
> fix(ecau): wrap long URLs in logging banners

- src/lib/util/array.ts
- src/mb_enhanced_cover_art_uploads/App.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
Moving the direct image fetching log message to the caller instead of the fetcher since the caller knows how many URLs need to be processed whereas the fetcher doesn't. It'd make a bit more sense to have it in the fetcher, but that'd require more refactoring that I don't want to do right now.
> fix(ecau): indicate progress when fetching single images

- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- tests/test-data/__recordings__/vgmdb-provider_1905514784/extracting-images_1310741912/extracts-covers-for-release-with-NSFW-cover_3684978920.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
When NSFW images are not enabled in a user's preferences, the main cover art displayed on the VGMDB page is a placeholder. When fetching the images from MB when the user is logged in, this placeholder would be included alongside the "hidden" image (which is parsed from the sidebar).
When the user isn't logged in, the NSFW image may not be displayed at all unless a certain cookie is sent. However, for some reason, sending this cookie in the request is ignored. That should be fixed in the future, so we're warning about that now.
> fix(ecau): warn when NSFW cover is encountered, skip placeholder

- src/lib/util/xhr.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
In Violentmonkey, `finalUrl` on `GM.Response` can potentially be undefined, which previously led to crashes. Instead, we'll fall back on the original URL, but emit a warning when we could not detect potential redirects.
> fix(ecau): warn when redirect cannot be detected

- src/lib/util/async.ts
- src/lib/util/observable.ts
- src/mb_enhanced_cover_art_uploads/App.ts
- tests/unit/lib/util/async.test.ts
Promise#finally isn't supported in all browsers which we claim to support, so we'll use a polyfill instead of using it directly.
Closes #537.
> fix(ecau): don't use Promise#finally.

- .github/renovate.json
The config didn't allow renovate to create new pin dependency updates since there were existing PRs under the same name.
> build(deps): allow renovate to pin dependencies

- src/lib/util/xhr.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
- src/mb_enhanced_cover_art_uploads/providers/tidal.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/apple_music.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/bugs.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/datpiff.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/discogs.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/find_images_spec.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/melon.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/tidal.test.ts
Previously, when a release returned a 404 code, a generic HTTP error would be shown in the log. Changing this to be more specific and to include the provider name in the error message.
Not all providers have been changed though. Notably the Tidal provider will still throw a generic error because it performs custom requests. That remains to be fixed.
> refactor(ecau): standardise 404 error messages for providers

- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/maximise.ts
- tests/unit/mb_enhanced_cover_art_uploads/maximise.test.ts
\+ a follow-up to #541 where the logging code wasn't properly updated, leading to a warning for both "Could not determine whether redirected" and "Followed redirect to `undefined`" to display simultaneously.
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/105
> fix(ecau): skip maximised images which are actually videos

- src/lib/MB/types.ts
- src/mb_multi_external_links/index.ts
#512 fixed it for the release editor, but broke it for artists etc. Turns out the MBS change there only applied to the release editor, the other pages weren't affected by the new property.
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/105
> fix(split links): use correct ref on non-release pages

- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
Should fix all of the examples reported in https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/105?u=ropdebee except Front Tray and Back Tray. Those are possible, but it'd be super ugly in the current implementation. A massive refactoring is getting more and more necessary (I'm thinking: tokenize the captions and look for combinations of keywords instead of the unflexible first word + rest of the caption stuff it's doing now).
> fix(ecau): more improvements to VGMdb type mappings

- src/mb_enhanced_cover_art_uploads/providers/spotify.ts
The old URL is no longer working and the unbalanced look of the import buttons with one of the icons missing is annoying me.
> fix(ecau): update URL of Spotify favicon

- mb_supercharged_caa_edits.user.js
The script was also running in sub-frames since Violentmonkey 2.13.1, which prevented inline entity dialogs from being submitted.
Temporary fix for #569 until we have better match rules for this script.
> fix(caa-edits): Exclude inline entity creation dialogs

- src/mb_enhanced_cover_art_uploads/providers/base.ts
Bugs redirects to the mobile site on mobile devices, where the og:image property holds a relative URL. If we add the base URL of the page, it should be able to correctly resolve those.
See https://github.com/ROpdebee/mb-userscripts/issues/547#issuecomment-1272552566.
> fix(ecau): handle relative URLs in og:image providers

- .github/actions/setup/action.yml
- build/deploy.ts
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: use environment files instead of deprecated ::set-output

- build/deploy.ts
GitHub Actions did not like that the final EOF marker was preceded by whitespace.
> ci: fix deployment reporting

- build/check-scripts-unchanged.ts
- build/deploy.ts
- build/types-deploy.ts
- build/versions.ts
The continuous deployment checks whether changes have been made to the scripts and deploys an update if so. However, it was checking against the latest deployed version, rather than the "previous version". These two are different if the `skip cd` tag is used. This led the deployment to deploy updates for PRs that did not change the scripts at all, because an old, not-yet-deployed change was skipped previously.
Instead, we'll now check against the compiled scripts based on the "previous" commit ref. For pushes to main, this is the commit before the push (even when multiple commits are pushed); for deployment previews in PRs, this is the base branch of the PR; for checking for changes in automated dependency updates, this is the main branch.
This should fix #600.
To test this, we'll merge …
> ci(deploy): check for changes against base instead of previous deploy

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
- .github/workflows/renovate-check.yml
We were only fetching at depth 1, which meant we couldn't check out an older commit to compare compiled scripts during deployment.
_Seems like every time I change something about CI, I need to do a follow-up PR to fix a bug in CI 🤔_
> ci(deploy): fetch full repository history

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
- .github/workflows/renovate-check.yml
ugh.
I'm really tempted to just push to main directly instead of going through PRs, but without PRs deployment will error out as it can't find the PR info.
> ci(deploy): fix wrong param name to actions/checkout

- build/build.ts
- build/versions.ts
TL;DR: When comparing compiled scripts, we'll compile them in a child process and make sure that the dependencies are installed according to the lock file.
See #593.
> ci(deploy): detect changes caused by dependency versions

- .github/actions/setup/action.yml
Since we started using caching, the cache has grown in size 10-fold. Once we switched CI to use Node 18, all of a sudden cache size dropped substantially. The reason is that the npm cache is incremental, and it doesn't remove package downloads that we're no longer using. The cache therefore contains old package downloads that we haven't used in months, and that's slowing down CI since it takes longer to fetch and extract that cache.
Instead, we'll change the cache keys every month by having the keys depend on the current year and month. Therefore, we'll start off with a fresh cache on a monthly basis, and the cache won't waste unnecessary space any longer.
> ci: put npm cache on a monthly diet

- README.md
- build/build.ts
- build/generate-readme.ts
- build/plugin-userscript.ts
- build/versions.ts
- package-lock.json
- package.json
- src/lib/util/metadata.ts
- src/mb_caa_dimensions/meta.ts
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_multi_external_links/meta.ts
Instead of manually updating the information in the README, which can be cumbersome with all of the links, let's use a script to generate it automatically. It also supports the legacy JS scripts, so that should make it easier to do the TS migration for each script individually without needing to spend time changing the README.
I've also added a check to the build process so that the build (and by extension, CI) will fail if the README becomes outdated.
> build: generate README

- .github/renovate.json
With the overrides we specified, renovate applies lock file maintenance multiple times on the first day of the month. Instead, we'll override these options the correct way, which should inherit the standard scheduling semantics of `maintainLockFilesMonthly`.
> ci: smaller time window for renovate lock file maintenance

- tests/unit/mb_enhanced_cover_art_uploads/seeding/atisket/dimensions.test.ts
This reverts commit 0a104b762557185ba515fdb18f1c10d0be0dd5df.
The type declarations have been fixed so this additional verbosity is no longer necessary.
> revert: test(ecau): convince TS of jest mock types

- build/plugin-consts.ts
- build/rollup.ts
- package-lock.json
- package.json
Although the 3rd party version has been updated to support Rollup v3, the update hasn't been released yet after many months. This blocks our upgrade to Rollup 3 (#587). Since it's a very simple plugin, we can maintain our own copy.
Also improves the type declaration slightly to prevent passing in data which won't be injected properly, since it's using JSON.stringify internally.
> build: use local implementation of rollup-plugin-consts

- .github/renovate.json
The package update spam is getting out of hand, and the vast majority of recent commits are updates to dev dependencies. The previous config could make sense when the repo is very active, but this repo hasn't been very active in the past few months except for merging dependency updates. That maintenance effort is better spent elsewhere, so reducing the frequency of automated updates makes sense.
Patch and minor upgrades should all be grouped into a single monthly PR, and will be auto-merged if CI passes and the compiled scripts are unaffected. Major upgrades and any upgrade to production dependencies will still be raised as a PR, but also just once a month.
We're explicitly ignoring one package due to #624, so if a future update to that package is available, it'll still be a separate PR. …
> ci: configure renovate to create a single PR per month

- src/mb_enhanced_cover_art_uploads/fetch.ts
- tests/unit/mb_enhanced_cover_art_uploads/fetch.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/test-utils/dummy-data.ts
Discogs has started to rate-limit image requests. Adding a retry-loop with exponential backoff on 429/5xx HTTP errors should alleviate most of these issues, and will work for other providers too.
Manually tested on a release with 47 Discogs images. 5 retries is not enough, but 10 seems to work.
Fixes #668.
> fix(ecau): retry loading image contents on certain HTTP errors

- .github/renovate.json
Seems like renovate hasn't been running the past few months because the default "monthly" schedule is set to be "before 4am on the first day of the month" but checking the logs, it only started running at 7am UTC today. Let's give it the entire day instead, just to make sure it runs when it should.
> ci: allow renovate more time to run

- .github/workflows/CI.yml
renovate-check is also running this job. We can't remove it from renovate-check because otherwise it won't run without a PR. It needs to run without a PR for automerge.
> ci: don't run build-and-test twice for renovate updates

- .github/renovate.json
Same reason as #677, but instead of allowing the whole day, we'll only allow it in the morning. Otherwise it may create multiple commits in the same day. It might still do so, but at least it won't be doing to the entire day.
> ci: larger schedule for renovate lock file maintenance

- src/lib/util/blob.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
It appears that Violentmonkey's implementation of `GM.xhr` with a blob `responseType` causes the blob to become unloaded if the response itself goes out of scope. When that happens, the image we enqueued for uploading will become empty, and the upload will fail. To prevent this from happening, we'll instead copy the buffer, which should prevent the contents from being unloaded.
> fix(ecau): prevent image blob from unloading before upload

- .github/workflows/build-and-test.yml
Codecov uploads are a bit flaky. Uploading the coverage data in a separate job allows us to fail and re-run that job and that job only, without needing to re-run tests. Also use token to avoid most upload flakes.
> ci: upload codecov coverage data in separate job

- src/lib/MB/CoverArt.ts
- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- tests/test-data/__recordings__/musicbrainz-provider_2175364407/extracting-images_1310741912/extracts-covers-for-release-with-complex-artwork-types_3075974168.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/musicbrainz.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
"Matrix/Runout" and "Raw/Unedited" could not be copied when a MB release's images were copied because the enum used the "Matrix" and "Raw" keys only. Instead, we'll use the full artwork type name as keys. This also requires changes in VGMdb's caption to artwork type mappings and related tests. Also add test case with a real release.
Fixes #708
> fix(ecau): copy MusicBrainz complex artwork types

- .browserslistrc
- babel.config.cjs
- package-lock.json
- package.json
- src/lib/util/domain_dispatch.ts
- src/mb_enhanced_cover_art_uploads/maximise.ts
Going forward, we'll only support browsers versions released since 2021. These changes should reduce the size of the transpiled scripts substantially.
> build: update minimum required versions of browsers

- lib/work_identifiers.js
- mb_bulk_copy_work_codes.user.js
- mb_validate_work_codes.user.js
SPA IDs are sequential numbers. Sometime within the last 2.5 years, the 10 millionth SPA ID was issued, which means that an increasing amount of IDs are now 8 characters long instead of 7. However, the script associated with this library currently only looks for 7 digits, and presents (incorrect) validation errors for 8-digit SPA IDs. This change aims to ameliorate that by increasing the character length the regex allows for.
> fix: increase SPA ID length limit for work code validation

- src/mb_enhanced_cover_art_uploads/providers/discogs.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/discogs.test.ts
Fixes #758
Some tests are disabled because the HTTP recordings are wrong and cannot be regenerated easily because Discogs seems to have added Cloudflare protection. I'll fix that later.
> fix(ecau): hotfix for Discogs query SHA

- mb_qol_inline_recording_tracks.user.js
I noticed that this userscript relies on mb_INLINE-STUFF to run properly.
Example release with no AR, no AcoustID and no ISRC (quick! it is being removed!)
https://musicbrainz.org/release/1f3a402f-7265-42ea-803a-f3cf8c508e7c
Or any other releases with credits at bottom and no mb_INLINE-STUFF running
https://musicbrainz.org/release/b4e8f7f4-e35c-42eb-a043-9605e4784aff
> fix(inline recs): Crash when no existing div.ars

- .github/renovate.json
We're failing to keep up with the automated dependency updates anyway, so let's prevent the spam and clear up bandwidth for important updates instead.
> ci: disable renovate "temporarily"

- src/mb_caa_dimensions/index.ts
- src/mb_caa_dimensions/style.scss
Since event art went live, the classname for cover art images was changed, causing the script to not detect most images anymore. We'll use both classnames for now, since the production MBS still uses the old one, but the query can be simplified later.
> fix(caa dims): compatibility with new beta.MBS

- build/plugin-userscript.ts
I already did this in #34, but it was reverted when we switched from ESM to CJS in #147.
Now that a2e7fc7 reintroduced ESM with `tsx`, we need this patch again.
See the problem discussion at https://github.com/ROpdebee/mb-userscripts/pull/779#issuecomment-2242718714 and https://github.com/kellnerd/userscript-bundler/issues/4.
> build: Fix dynamic import of metadata modules on Windows (again)

- mb_qol_inline_recording_tracks.user.js
Remove `:first-child`, not needed and blocking video recordings detection
The selector is already strict enough to not catch recordings from `div.ars` (I guess it was the reason for those)
Examples where video data track was not handled before this commit: https://musicbrainz.org/release/d9e494dd-9386-48e4-8c52-9764dd8b8a0f
https://musicbrainz.org/release/0a5be94f-3429-46bd-9b1d-07dcb0209098
Release with recordings in inline relationships (on CD 23): https://musicbrainz.org/release/70dcde39-81ed-45e8-bdb3-f511112a3880
There was not problem with non-video data tracks:
https://musicbrainz.org/release/b63ca2ff-782e-45fc-bfb9-b74dc6aefe00
---
@ROpdebee, may I leave you manage the version number, OK?
My 3 concurrent PR have no conflict between themselves:
- #764
- This
- #777
> fix(inline recs): Handle video recordings

- mb_qol_inline_recording_tracks.user.js
Exclude rule syntax is like include, not like match (//*.mb.org does not match //mb.org, only test.mb.org, beta.mb.org) Before this commit, exclude rules are not applied to main //mb.org website
I am also excluding more unrelated pages (open edits, edit history page 2+, details, cover arts, ...)
Add mb.eu support
---
@ROpdebee, may I leave you manage the version number, OK?
My 3 concurrent PR have no conflict between themselves:
- #764
- #776 
- This
> fix(inline recs): Fix mb.org exclude rules and add mb.eu match rule

- src/mb_caa_dimensions/image.ts
- src/mb_caa_dimensions/meta.ts
- src/mb_caa_dimensions/style.scss
@vzell request:
> https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/182
>
> Could the userscript **MB: Display CAA image dimensions** be extended to the new event-art-archive?
Tested on https://musicbrainz.org/event/d1bd6d40-55f6-4e1a-91df-4c9395f95401 and sub-pages (/event-art, /edits)
> feat(caa dims): add support for new event art archive (EAA)

- mb_qol_inline_recording_tracks.user.js
For the moment, release tracks were displayed in random order.
Now they will be ordered by date, then title, then comment.
I have also added display of release comment and added release date as tooltip.
---
@ROpdebee, may I leave you manage the version number, OK?
My 3 concurrent PR have no conflict between themselves:
- This
- #776 
- #777
> feat(inline recs): Order tracks by ascending release dates

- package-lock.json
Update nativejsx to trim extraneous whitespace. An example of the bug can be seen in the recent caa_dims changelog notifications, where there's a space before the period after the anchor. Normal JSX allegedly removes such whitespace, so we should too.
> fix: remove extraneous spacing in JSX-transpiled HTML

- package-lock.json
- src/mb_enhanced_cover_art_uploads/seeding/parameters.ts
When ECAU is injected in the content context in Firefox, it uses the `URLSearchParams` from the page context via an x-ray. However, a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1023984) prevents us from iterating through the result of the `entries()` call. Instead, we can iterate through the `URLSearchParams` directly.
Fixes #773.
> fix(ecau): fix seed parameters not iterable error

- src/mb_enhanced_cover_art_uploads/providers/rateyourmusic.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/rateyourmusic.test.ts
We only supported "single" and "album" URLs in the past, but there can be many more release types (e.g., "ep", "musicvideo", "comp", "additional").
Nonetheless, RYM support might be broken entirely, as the JPEG images we sought previously are now locked behind a captcha. Even simply requesting a page is leading to a Cloudflare 403 page on my end, and the necessary cookies to bypass those pages aren't getting injected into the requests for some reason 🤷
Fixes #756.
> fix(ecau): support more RateYourMusic release types

- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/seeding/harmony/index.tsx
- src/mb_enhanced_cover_art_uploads/seeding/index.ts
Added support for harmony.pulsewidth.org.uk to the Enhanced Cover Art Uploads userscript. This allows users to easily add cover art from the Harmony importer to MusicBrainz releases with a single click, similar to the existing a-tisket integration.
> feat(ecau): Seed cover art from Harmony release actions pages

- mb_bulk_copy_work_codes.user.js
Replaced table field selector `PREFERRED_ISWC_FIELD` with `ISWC_FIELD`
> fix(work codes): Update ISWC table selector on https://iswcnet.cisac.org/search

- package-lock.json
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/seeding/atisket/index.tsx
- src/mb_enhanced_cover_art_uploads/seeding/dimensions.ts
- src/mb_enhanced_cover_art_uploads/seeding/harmony/index.tsx
- tests/unit/mb_enhanced_cover_art_uploads/seeding/dimensions.test.ts
With the latest changes to the Harmony website to make extraction of the necessary data more reliable, seeding of release URLs instead of image URLs became simpler to implement.
Image dimensions are now displayed there as well, making use of the already existing code for the a-tisket seeder.
> feat(ecau): Display image dimensions and seed release URLs from Harmony

- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/clears-the-cache-entry-on-failure_963532173.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-for-subsequent-requests_598889563.warc
- tests/test-data/__recordings__/discogs-provider_883142520/caching-API-responses_1012471802/reuses-the-cache-entry-while-maximising-images_2688171962.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/extracts-covers-for-release_2308446907.warc
- tests/test-data/__recordings__/discogs-provider_883142520/extracting-images_1310741912/throws-on-non-existent-release_1189313548.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/discogs.test.ts
They were disabled a while ago in #762 because of Cloudflare protection. Now that we have the recording replacer script from #816, we can actually update the recordings and start using the tests again.
Also updated the negative test case as it pointed to a release that now exists. The new ID is the largest ID that the API currently accepts.
> test(ecau): fix Discogs tests

- src/lib/compat.ts
- src/lib/config.ts
- src/mb_enhanced_cover_art_uploads/app.ts
- src/mb_enhanced_cover_art_uploads/config.ts
- src/mb_enhanced_cover_art_uploads/fetch.ts
- src/mb_enhanced_cover_art_uploads/meta.ts
- src/mb_enhanced_cover_art_uploads/providers/bandcamp.ts
- src/mb_enhanced_cover_art_uploads/providers/base.ts
- src/mb_enhanced_cover_art_uploads/providers/soundcloud.ts
- src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts
- src/mb_enhanced_cover_art_uploads/seeding/vgmdb.tsx
- src/mb_enhanced_cover_art_uploads/ui/main.scss
- src/mb_enhanced_cover_art_uploads/ui/main.tsx
- src/mb_multi_external_links/index.ts
- tests/unit/lib/config.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/config.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/fetch.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/bandcamp.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/find-images-spec.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/soundcloud.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
- tests/unit/utils/gm-mocks.ts
- tests/unit/utils/setup-gm-mocks.ts
Add various configuration options:
- Global + provider-specific option to skip extracting track images, separately from choosing whether to only extract the front covers.
- VGMdb: Option to keep entire comment (closes #657)
- Bandcamp: Option to put square crop before the original, non-square cover art (closes #443).
These configuration options are consolidated in a single configuration object and configurable from a new collapsible drop-down in the UI.
Known limitations:
- Getting and setting the options is asynchronous because it requires GM.get/setValue, which are also async. This causes some functions to be async only because they need to read config options, which is a pity.
- There's some code duplication between the config and the UI, in that both need to specify the same …
> feat(ecau): configuration options

- src/lib/util/array.ts
- src/mb_enhanced_cover_art_uploads/providers/soundcloud.ts
- tests/test-data/__recordings__/soundcloud-provider_749668182/extracting-images_1310741912/grabs-no-images-if-track-has-no-image_2364970469.warc
- tests/unit/lib/util/array.test.ts
- tests/unit/mb_enhanced_cover_art_uploads/providers/soundcloud.test.ts
The API returns an error if more than 50 track IDs are provided.
Includes a disabled test case which requires #765 to be implemented, otherwise the recordings will be far too big. Also fixes an unrelated test case.
Fixes #790.
> fix(ecau): extract track images for Soundcloud sets with >50 tracks

- .github/renovate.json
Renovate is scheduled to only run on Feb 29th, which is once every 4 years. I'm hoping that this will have the following effect:
- Renovate will not create update commits or PRs except one day of the year, thereby reducing its spam.
- Renovate will still monitor for updates and maintain its dependency dashboard, where the available updates will be marked as "awaiting schedule" and PRs can be created on demand.
Effectively, if this works, we'll be able to have an overview of outdated dependencies, while also being able to manually curate which pending updates we want to apply, all without a constant barrage of automated commits on a dormant repository, or a constant barrage of PR update e-mails. 🤞. As far as I know, there is no way to configure Renovate in such a way.
Also removing the …
> chore(build): re-enable renovate on-demand

- package-lock.json
- package.json
These are deprecated as the respective packages ship their own type definitions.
> chore(deps): remove deprecated `@types` packages

- .eslintrc.cjs
- configs/eslint/deprecation.cjs
- package-lock.json
- package.json
This plugin is itself deprecated, as the check has been integrated into typescript-eslint. This plugin is also preventing ESLint from being updated to a newer version.
> chore(deps): remove eslint-plugin-deprecation

- src/mb_enhanced_cover_art_uploads/providers/bandcamp.ts
- tests/test-data/__recordings__/bandcamp-provider_3598072612/extracting-images_1310741912/extracts-covers-for-subscriber-only-releases_4211089645.warc
- tests/test-data/__recordings__/soundcloud-provider_749668182/extracting-images_1310741912/does-not-load-all-track-images-if-some-could-not-be-loaded_3382566896.warc
- tests/unit/mb_enhanced_cover_art_uploads/providers/bandcamp.test.ts
The embedded player may be unavailable, e.g., on subscriber-only releases. We can still load some cover art from those, so we'll avoid erroring out when that happens.
The track images could technically be added using the old approach of loading the track pages directly, but since I expect the combination of subscriber-only releases AND track-specific images to be rare, I'm opting to omit this functionality for now.
Note: Not sure why the Soundcloud recordings changed.
Fixes #843
> fix(ecau): gracefully handle failures in Bandcamp track image extraction

- src/mb_enhanced_cover_art_uploads/providers/spotify.ts
As [described in the forum](https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/210?u=chaban), Spotify is messing with the Open Graph tags. Apparently simply omitting the User-Agent header fixes this problem.
> fix(spotify): remove User-Agent header
