README.md, mb_bulk_copy_work_codes.user.js
Just found a typo in the README and decided to run the spell checker of my IDE over the code as I still had it open. In case you are using VS Code I can also share the workspace dictionary with some words I marked as exceptions.
=> Run a spell checker and fix typos

src/mb_enhanced_cover_art_uploads/meta.ts
=> Testing deployment against protected branch

.github/commit_release.ts, src/mb_enhanced_cover_art_uploads/meta.ts
=> Autorelease test again

.github/commit_release.ts, src/mb_enhanced_cover_art_uploads/meta.ts
will this be the last one? who knows.
=> Autorelease test number 3

src/mb_enhanced_cover_art_uploads/supportedProviders.md
=> Make note of VGMdb limitation in provider docs

mb_bulk_copy_work_codes.user.js
Add support for languages other than English on ISWCNet.
When solving the captcha, ISWCNet presents you with a language choice. The language code gets stored into session storage under the name `culture`. That item is used to request `https://iswcnet.cisac.org/configuration/GetLocalizedStrings` which returns the translations for the given "culture" (i.e., language). The results are JSON-serialized and stored into local storage under the key `strings`.
We're using that local storage item to translate the necessary text so that we can properly extract information on non-English ISWCNet pages. Since class names seem auto-generated and may be subject to change, matching DOM elements works through scanning for elements with a certain text, and therefore we need the correct translations. …
=> Support other languages on ISWCNet

.eslintrc.cjs, package-lock.json, package.json, src/mb_enhanced_cover_art_uploads/index.ts
This will hopefully prevent issues like the one from #201
=> style: disallow use of confusing window globals

README.md
Closes #221.
I'll also add a link to the instructions in the README of the `dist` branch after merge.
=> docs: include installation instructions

babel.config.cjs, build/plugin-userscript.ts
Per discussion at https://github.com/ROpdebee/mb-userscripts/commit/d925bda961c2048575e38317b3e67d85e886ec0a#r62233622
=> build: remove comments and point to GitHub sources in compiled scripts

mb_qol_seed_recording_disambiguation.user.js
=> fix(qol): add exception for Washington DC in live comment seeder

build/report-deploy.js
=> ci: fix deployment reporting again

mb_bulk_copy_work_codes.user.js
=> fix(work codes): deduplicate normalised/dirty codes

src/mb_enhanced_cover_art_uploads/providers/qobuz.ts, tests/test-data/__recordings__/qobuz-provider_3453546435/extracting-images_1310741912/falls-back-to-URL-rewriting-when-API-returns-404_1187337482.warc, tests/unit/mb_enhanced_cover_art_uploads/providers/qobuz.test.ts, tests/unit/mb_enhanced_cover_art_uploads/providers/qub_musique.test.ts
=> fix(ecau): fall back to URL rewriting when Qobuz API returns 404

src/mb_enhanced_cover_art_uploads/providers/qobuz.ts, tests/unit/mb_enhanced_cover_art_uploads/providers/qobuz.test.ts
=> fix(ecau): ignore Qobuz goodies without URL

src/mb_enhanced_cover_art_uploads/index.ts, src/mb_enhanced_cover_art_uploads/meta.ts, src/mb_enhanced_cover_art_uploads/seeding/index.ts, src/mb_enhanced_cover_art_uploads/seeding/musicbrainz.tsx
=> feat(ecau): add provider buttons to main cover art page

mb_caa_dimensions.user.js
Fixes #425.
I've done a quick test, but please test thoroughly 🙃
=> feat(CAA dimensions): remove jquery

src/mb_enhanced_cover_art_uploads/meta.ts
https://github.com/qsniyg/maxurl/commit/ed7aec8c88b3a67a692ff101935889c2c884c13d
https://github.com/qsniyg/maxurl/commit/35439bee85857e2d727b977e2ffabd1749fde294
I didn't personally test this, so it might still require one of those grants somewhere...
=> build(ecau): bump IMU, remove unnecessary grants

mb_supercharged_caa_edits.user.js
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/67
=> feat(caa edits): add clamshell packaging type

src/lib/update-notifications/index.tsx
https://github.com/ROpdebee/mb-userscripts/pull/458#discussion_r893368171
=> fix: don't show update notifications when there are no new features

build/tsconfig.json, package-lock.json
=> build: re-enable TypeScript `.d.ts` checking

src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts, tests/test-data/__recordings__/vgmdb-provider_1905514784/extracting-images_1310741912/extracts-covers-for-release-without-any-cover-or-picture_2065586161.warc, tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
=> fix(ecau): support vgmdb releases without covers

mb_qol_inline_recording_tracks.user.js
Fixes #484.
Dropping jQuery since I'm pretty sure that's what's causing the `recAnchors is not iterable` error, probably another conflict with another jQuery version, possibly MB's own jQuery even.
As a quick-fix for the hydration errors, we're now delaying the insertion of the button until the window is fully loaded. Since hydration is done synchronously, it should already be done before this event occurs.
=> fix(inline recs): prevent hydration errors, drop jQuery

src/mb_caa_dimensions/Image.ts
Just had an upload that showed `0x0`.
=> fix(caa dims): wait until dimensions are known on queued uploads

src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts, tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
Remove unnecessary parentheses, braces, brackets, and dashes.
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/90?u=ropdebee
=> fix(ecau): clean up VGMdb captions

src/mb_enhanced_cover_art_uploads/providers/bandcamp.ts, tests/test-data/__recordings__/bandcamp-provider_3598072612/extracting-images_1310741912/skips-grabbing-square-thumbnails-if-dimensions-cannot-be-loaded_3362680250.warc, tests/unit/mb_enhanced_cover_art_uploads/providers/bandcamp.test.ts
Most likely the image itself won't be able to load later either, but this at least gets rid of a poor error message.
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/92?u=ropdebee
=> fix(ecau): skip adding Bandcamp square thumbs if dimensions cannot be loaded

src/mb_multi_external_links/index.ts
Previously, we patched the editor to show only the first URL, and submit the rest of the links when the first one is submitted. This also led to problems when the user changed the first URL, as the remaining URLs would be forgotten.
Instead, we'll submit all but the last URLs immediately when they're pasted, and leave the last URL as pending. This provides a better UX.
Fixes issue reported by chaban in forums: https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/84
=> fix(split links): submit all but last URL immediately

src/mb_enhanced_cover_art_uploads/seeding/atisket/index.tsx
a-tisket can sometimes suggest multiple releases, e.g. https://atisket.pulsewidth.org.uk/?deez_id=507397
Up until now, we only generated one seed link for the first release. This can lead users to accidentally upload the same image twice, thinking they're adding it to different releases.
Instead, we'll now add multiple seed links if there are multiple release suggestions, and distinguish them by the first chunk of their MBID. The MBID is only included when there are multiple releases.
=> fix(ecau): handle multiple a-tisket release suggestions

src/lib/MB/CoverArt.ts, src/mb_enhanced_cover_art_uploads/providers/vgmdb.ts, tests/unit/mb_enhanced_cover_art_uploads/providers/vgmdb.test.ts
* More whitespace trimming
* Support colons to separate type from comment
* Map disc matrix/runout types
* Map packaging top/bottom types
* Improved mapping of digipak/slipcase faces
* More edge cases
* Include medium type for discs with sequence numbers
=> fix(ecau): improve VGMdb caption mapping

src/mb_enhanced_cover_art_uploads/providers/amazon.ts
=> fix(ecau): improve error message on Amazon captchas

mb_supercharged_caa_edits.user.js
I forgot to do this in #574, blame the automatic deployment of the other scripts 😂
=> chore(caa-edits): Bump version

tests/unit/lib/util/array.test.ts
While scrolling through coverage data, I noticed a dead spot here which is easy enough to fix.
=> test(lib): add tests for array/insertBetween

src/mb_enhanced_cover_art_uploads/meta.ts
=> fix(ecau): bump IMU to latest version

src/mb_enhanced_cover_art_uploads/providers/beatport.ts
=> fix(ecau): update Beatport favicon

src/mb_enhanced_cover_art_uploads/meta.ts
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/185
=> feat(ecau): update Image Max URL to maximise Spotify covers

src/mb_caa_dimensions/displayed-image.tsx
https://tickets.metabrainz.org/browse/MBS-13698
=> fix(caa dims): don't displace arrows on queued uploads

src/mb_enhanced_cover_art_uploads/providers/discogs.ts
=> fix(ecau): update Discogs query hash again

lib/work_identifiers.js, mb_bulk_copy_work_codes.user.js, mb_validate_work_codes.user.js
=> fix(work codes): add ACUM ID
